packages: []
shamefullyHoist: true
onlyBuiltDependencies:
  - esbuild
  - "@parcel/watcher"
allowBuilds:
  esbuild: true
  "@parcel/watcher": true
  vue-demi: false
minimumReleaseAgeExclude:
  - undocs-nightly@0.10.1-20260810-080950-9339f88 || 0.10.1-20260817-221446-007ca31
